"""empty message

Revision ID: 16b4c0795096
Revises: c4cc79d2ae52
Create Date: 2023-03-11 15:59:32.065769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b4c0795096'
down_revision = 'c4cc79d2ae52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_commodity')
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('commodity_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity_price', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('close')
        batch_op.drop_column('low')
        batch_op.drop_column('high')
        batch_op.drop_column('open')

    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('_alembic_tmp_commodity',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
