"""Initial migration.

Revision ID: c4cc79d2ae52
Revises: 
Create Date: 2023-03-11 15:56:11.714104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cc79d2ae52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('commodity_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity_price', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('close')
        batch_op.drop_column('low')
        batch_op.drop_column('high')
        batch_op.drop_column('open')

    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
